const PREFIX = '[CURRENCY]';

export const GET_CURRENCIES = `${PREFIX} GET_CURRENCIES`;
export const CONVERT_CURRENCY = `${PREFIX} CONVERT_CURRENCY`;
export const ADD_ACTION_HISTORY = `${PREFIX} ADD_ACTION_HISTORY`;
export const RESET_HISTORY = `${PREFIX} RESET_HISTORY`;
